title: "A Discovery of "
description: A website with a blog
footer_text: Copyright 2020 hlundyates
header_feature_image: ../uploads/anete-lusina-zwshjake_ii-unsplash.jpg
header_text: "A Discovery of "
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
